In [20]:
import seaborn as sns
df = sns.load_dataset('tips')

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [22]:
# to check how many day count are there in dataset
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [23]:
### dependent and independent features 
X = df[['total_bill','tip', 'sex', 'smoker',  'time', 'size']]
y = df['day']

In [24]:
## train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [25]:
X_train

     total_bill   tip     sex smoker    time  size
171       15.81  3.16    Male    Yes  Dinner     2
89        21.16  3.00    Male     No   Lunch     2
157       25.00  3.75  Female     No  Dinner     4
219       30.14  3.09  Female    Yes  Dinner     4
234       15.53  3.00    Male    Yes  Dinner     2
..          ...   ...     ...    ...     ...   ...
67         3.07  1.00  Female    Yes  Dinner     1
192       28.44  2.56    Male    Yes   Lunch     2
117       10.65  1.50  Female     No   Lunch     2
47        32.40  6.00    Male     No  Dinner     4
172        7.25  5.15    Male    Yes  Dinner     2

[183 rows x 6 columns]

In [26]:
y

0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
       ...
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: category
Categories (4, str): ['Thur', 'Fri', 'Sat', 'Sun']

In [27]:
## In this case we are  pickup all the features which are binary
#  we going to apply lable encoding and excluding binary apply One Hot Encoding

from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings('ignore') # to hide pandas SettingWithCopy warnings

In [28]:
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

In [29]:
# 1. Transform X_train (using fit_transform)
X_train['sex'] = le1.fit_transform(X_train['sex'])
X_train['smoker'] = le2.fit_transform(X_train['smoker'])
X_train['time'] = le3.fit_transform(X_train['time'])

# 2. Transform X_test (using transform ONLY to prevent data leakage)
X_test['sex'] = le1.transform(X_test['sex'])
X_test['smoker'] = le2.transform(X_test['smoker'])
X_test['time'] = le3.transform(X_test['time'])

In [30]:
X_train.head()

     total_bill   tip  sex  smoker  time  size
171       15.81  3.16    1       1     0     2
89        21.16  3.00    1       0     1     2
157       25.00  3.75    0       0     0     4
219       30.14  3.09    0       1     0     4
234       15.53  3.00    1       1     0     2

In [31]:
X_test.head()

     total_bill   tip  sex  smoker  time  size
64        17.59  2.64    1       0     0     3
63        18.29  3.76    1       1     0     4
55        19.49  3.51    1       0     0     2
111        7.25  1.00    0       0     0     1
225       16.27  2.50    0       1     1     2

In [32]:
y

0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
       ...
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: category
Categories (4, str): ['Thur', 'Fri', 'Sat', 'Sun']

In [33]:
# For the target variable 'day' (y), we use Label Encoding
le_y = LabelEncoder()

# Use fit_transform on the training set
y_train = le_y.fit_transform(y_train)

# Use transform ONLY on the testing set
y_test = le_y.transform(y_test)

In [35]:
y_test

array([1, 1, 2, 1, 0, 0, 1, 2, 2, 2, 1, 1, 2, 3, 0, 2, 3, 1, 3, 2, 1, 1,
       3, 2, 3, 3, 0, 3, 2, 1, 1, 3, 2, 1, 2, 2, 1, 3, 1, 0, 0, 3, 1, 2,
       1, 2, 1, 2, 1, 2, 3, 2, 1, 2, 2, 0, 2, 1, 3, 2, 0])

In [36]:
##1. Train the Naive Bayes Model
from sklearn.naive_bayes import GaussianNB

# Initialize the model
gnb = GaussianNB()

# Train the model on the training data
gnb.fit(X_train, y_train)

GaussianNB()

In [37]:
# Predict the output on the testing data
y_pred = gnb.predict(X_test)

In [38]:
y_pred

array([2, 1, 2, 1, 3, 1, 1, 1, 1, 1, 1, 1, 2, 3, 3, 2, 3, 2, 2, 1, 1, 2,
       3, 2, 3, 3, 3, 3, 2, 1, 1, 3, 1, 1, 2, 2, 2, 3, 1, 3, 3, 3, 1, 2,
       1, 2, 2, 2, 2, 2, 3, 1, 1, 2, 1, 1, 2, 2, 3, 2, 1])

In [39]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [40]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[ 0  0  0  0]
 [ 3 13  7  0]
 [ 0  7 14  1]
 [ 5  0  0 11]]
0.6229508196721312
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.65      0.57      0.60        23
           2       0.67      0.64      0.65        22
           3       0.92      0.69      0.79        16

    accuracy                           0.62        61
   macro avg       0.56      0.47      0.51        61
weighted avg       0.73      0.62      0.67        61

In [41]:
import pandas as pd

print("--- 📝 Enter Customer Details ---")

try:
    # 1. Ask the user for inputs at runtime
    total_bill = float(input("Enter Total Bill (e.g. 25.50): "))
    tip = float(input("Enter Tip Amount (e.g. 5.00): "))
    size = int(input("Table Size (number of people, e.g. 2): "))
    
    # We use .strip().capitalize() so that if you type "male" or " male ", it fixes it to "Male"
    sex = input("Enter Sex (Male/Female): ").strip().capitalize()
    smoker = input("Smoker? (Yes/No): ").strip().capitalize()
    time = input("Time of meal (Lunch/Dinner): ").strip().capitalize()

    # 2. Package it into a DataFrame exactly how the model expects it
    user_input = pd.DataFrame({
        'total_bill': [total_bill],
        'tip': [tip],
        'sex': [sex],
        'smoker': [smoker],
        'time': [time],
        'size': [size]
    })

    # 3. Encode the text inputs into numbers using your existing LabelEncoders
    user_input['sex'] = le1.transform(user_input['sex'])
    user_input['smoker'] = le2.transform(user_input['smoker'])
    user_input['time'] = le3.transform(user_input['time'])

    # 4. Make the Prediction
    predicted_numeric_day = gnb.predict(user_input)
    
    # Convert the numeric prediction back to text ('Sun', 'Thur', etc.)
    predicted_text_day = le_y.inverse_transform(predicted_numeric_day)

    print("\n" + "="*45)
    print(f"🤖 The model predicts this meal happened on: {predicted_text_day[0]}")
    print("="*45)

except ValueError:
    print("\n❌ Error: Please make sure you enter numbers for the Bill, Tip, and Size!")
except Exception as e:
    print(f"\n❌ Error: Please check your spelling for the text inputs. Details: {e}")

--- 📝 Enter Customer Details ---

=============================================
🤖 The model predicts this meal happened on: Thur
=============================================